// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/thriftrw/thriftrw-go/plugin/api (interfaces: ServiceGenerator)

package plugin

import (
	gomock "github.com/golang/mock/gomock"
	api "github.com/thriftrw/thriftrw-go/plugin/api"
)

// Mock of ServiceGenerator interface
type MockServiceGenerator struct {
	ctrl     *gomock.Controller
	recorder *_MockServiceGeneratorRecorder
}

// Recorder for MockServiceGenerator (not exported)
type _MockServiceGeneratorRecorder struct {
	mock *MockServiceGenerator
}

func NewMockServiceGenerator(ctrl *gomock.Controller) *MockServiceGenerator {
	mock := &MockServiceGenerator{ctrl: ctrl}
	mock.recorder = &_MockServiceGeneratorRecorder{mock}
	return mock
}

func (_m *MockServiceGenerator) EXPECT() *_MockServiceGeneratorRecorder {
	return _m.recorder
}

func (_m *MockServiceGenerator) Generate(_param0 *api.GenerateServiceRequest) (*api.GenerateServiceResponse, error) {
	ret := _m.ctrl.Call(_m, "Generate", _param0)
	ret0, _ := ret[0].(*api.GenerateServiceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockServiceGeneratorRecorder) Generate(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Generate", arg0)
}
