// Automatically generated by MockGen. DO NOT EDIT!
// Source: go.uber.org/thriftrw/ast (interfaces: Visitor)

package ast

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of Visitor interface
type MockVisitor struct {
	ctrl     *gomock.Controller
	recorder *_MockVisitorRecorder
}

// Recorder for MockVisitor (not exported)
type _MockVisitorRecorder struct {
	mock *MockVisitor
}

func NewMockVisitor(ctrl *gomock.Controller) *MockVisitor {
	mock := &MockVisitor{ctrl: ctrl}
	mock.recorder = &_MockVisitorRecorder{mock}
	return mock
}

func (_m *MockVisitor) EXPECT() *_MockVisitorRecorder {
	return _m.recorder
}

func (_m *MockVisitor) Visit(_param0 Walker, _param1 Node) Visitor {
	ret := _m.ctrl.Call(_m, "Visit", _param0, _param1)
	ret0, _ := ret[0].(Visitor)
	return ret0
}

func (_mr *_MockVisitorRecorder) Visit(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Visit", arg0, arg1)
}
